language: php

php:
  - 5.5
  - 5.6
  - 7.0

sudo: false

install:
  - phpenv config-rm xdebug.ini
  - travis_retry composer install --no-interaction --prefer-dist

script: composer run coverage

after_script:
  - vendor/bin/test-reporter

cache:
  directories:
    - vendor
    # - vendor/bundle
    # - $HOME/.cache/bower
    # - $HOME/.cache/pip
    # - $HOME/.ccache
    - $HOME/.composer/cache
    # - $HOME/.npm
    # - $HOME/.nvm
